### ISSUE TITLE
Factor out core library for parsing and decryption

### ISSUE THREAD

**Issue by crumblingstatue** [spd789562/wz-reader-rs#6]
I would like to experiment with a different way of storing a wz node graph than `Arc<RwLock>`, but it's kind of baked into the structure of the library currently.

I was thinking about forking `wz-reader-rs` and factoring out the parsing and decryption portion as a reusable crate.

Is there any interest in upstreaming such work?

**Comment by spd789562** [comment]
yes, but no, I'm do have ideas to refactoring this crate to workspace and separate to something like
- wz_reader_rs_core(base node and stuff)
- wz_reader_rs_property
- wz_reader_rs_reader/store
- wz_reader_rs_writer
- wz_reader_rs_parse
- wz_reader_rs_png (image parsing stuff)
- wz_reader_rs_util

not sure is reasonable tho.

And for node part, since im not good at unsafe code and I'm a node been locked by parsing or something(for concurrent reason)
so that what i'm ended up with, but still think some thing like use `left_right` and use `Arc<ReadHandle, WriteHandle>` or better way.

But it all just idea :/, recent frequently working on [MapleCharacterCreator](https://github.com/spd789562/MapleCharacterCreator) a tool to preview clothing and dye item/hair stuff

Feel free to fork one or even create a new one! this project is more something like my rust learning journey, and it always fun to think what this project could be better

**Comment by crumblingstatue** [comment]
I think for the time being, I'll do a hard fork, because I have no idea how to factor out all the Arc/RwLock stuff without significant changes.

But maybe one day we can reconcile some common core stuff.

Thank you for letting me reuse your hard work!

**Comment by spd789562** [comment]
nice, wish you good luck!
